version: "3.8"

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Bighead123
      POSTGRES_DB: product
    ports:
      - "5432:5432"

  web:
    build: .
    environment:
      DATABASE_URL: "postgresql://postgres:Bighead123@localhost:5432/product"
    ports:
      - "8000:8000"
    depends_on:
      - db
